# Generated by Django 2.0.3 on 2018-08-08 09:51

from django.db import migrations
from django.contrib.postgres.fields.jsonb import *


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_auto_20181202_2057')
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_template',
            field=JSONField(blank=True, null=True, default={}, verbose_name='product_template'),
        ),
    ]
